const PRIMARK_SQM_RATE = 0.77;
const FACTORY_SQM_RATE = PRIMARK_SQM_RATE * 0.95;

const SUPPLIERS = {
  epyllion: {
    name: "Epyllion",
    formulaId: "epyllion",
    factories: [
      { name: "Fakir Knitwears Ltd.", rate: FACTORY_SQM_RATE },
      { name: "Well Lord Knitwear Limited", rate: FACTORY_SQM_RATE },
      { name: "Novel Hurricane Knit Garments Ltd.", rate: FACTORY_SQM_RATE },
      { name: "Hasan Tanvir Fashion Wears Limited", rate: FACTORY_SQM_RATE },
      { name: "MOUCHAK KNIT COMPOSITE LTD", rate: FACTORY_SQM_RATE },
      { name: "Habitus Fashions Limited", rate: FACTORY_SQM_RATE },
      { name: "L'ESQUIRE LIMITED", rate: FACTORY_SQM_RATE },
      { name: "Ibrahim Knit Garments (Pvt) Ltd.", rate: FACTORY_SQM_RATE },
      { name: "Surma Garments LTD", rate: FACTORY_SQM_RATE },
      { name: "PRUDENT FASHION LTD.", rate: FACTORY_SQM_RATE },
      { name: "Norp Knit Industries Ltd.", rate: FACTORY_SQM_RATE },
      { name: "Mehnaz Styles and Craft Ltd.", rate: FACTORY_SQM_RATE },
      { name: "Modele de Capital Ind Ltd.", rate: FACTORY_SQM_RATE },
      { name: "AST Knitwear Ltd.", rate: FACTORY_SQM_RATE },
      { name: "Fortis Garments Limited", rate: FACTORY_SQM_RATE },
      { name: "Soorty Textiles (BD) Limited", rate: FACTORY_SQM_RATE },
      { name: "Masco Cottons Ltd.", rate: FACTORY_SQM_RATE },
      { name: "Fame Apparels Limited", rate: FACTORY_SQM_RATE },
      { name: "Kaixi Lingerie Bangladesh Co. Limited", rate: FACTORY_SQM_RATE },
      { name: "Triple Apparels Limited", rate: FACTORY_SQM_RATE },
      { name: "Oxford Shirts Limited", rate: FACTORY_SQM_RATE },
      { name: "Comfit Composite Knit Limited", rate: FACTORY_SQM_RATE },
      { name: "Echotex Limited", rate: FACTORY_SQM_RATE },
      { name: "Scarlet Knitwears Limited", rate: FACTORY_SQM_RATE },
      { name: "Yunusco (BD) Ltd.", rate: FACTORY_SQM_RATE },
      { name: "International Classic Composite Limited", rate: FACTORY_SQM_RATE },
      { name: "Good Earth Apparels ltd.", rate: FACTORY_SQM_RATE },
      { name: "MB Knit Fashion Limited", rate: FACTORY_SQM_RATE },
      { name: "ALIM KNIT (BD) LTD.", rate: FACTORY_SQM_RATE },
      { name: "Progress Apparels (Bangladesh) Limited", rate: FACTORY_SQM_RATE }
    ]
  },
  mu: {
    name: "M&U",
    formulaId: "mu",
    factories: [
      { name: "Akh Eco Apparels Ltd", rate: FACTORY_SQM_RATE },
      { name: "Ananta Casual Wear Ltd", rate: FACTORY_SQM_RATE },
      { name: "Ananta Huaxiang Ltd", rate: FACTORY_SQM_RATE },
      { name: "Aspire Garments Ltd", rate: FACTORY_SQM_RATE },
      { name: "Azmat Apparels Ltd", rate: FACTORY_SQM_RATE },
      { name: "BANDO Eco Apparels Ltd", rate: FACTORY_SQM_RATE },
      { name: "BRAVO APPAREL MANUFACTURER LTD", rate: FACTORY_SQM_RATE },
      { name: "Brothers Fashion Ltd", rate: FACTORY_SQM_RATE },
      { name: "CA KNITWEAR LIMITED", rate: FACTORY_SQM_RATE },
      { name: "Chorka Textile Ltd", rate: FACTORY_SQM_RATE },
      { name: "COLOUR AND CO LTD", rate: FACTORY_SQM_RATE },
      { name: "Designtex Knitwear Ltd", rate: FACTORY_SQM_RATE },
      { name: "ECHOKNITS Ltd", rate: FACTORY_SQM_RATE },
      { name: "Fortis Garments Ltd", rate: FACTORY_SQM_RATE },
      { name: "Goumati Knit Wears Ltd", rate: FACTORY_SQM_RATE },
      { name: "Habitus Fashion Limited", rate: FACTORY_SQM_RATE },
      { name: "Hoplun Apparels Ltd", rate: FACTORY_SQM_RATE },
      { name: "Intimate Attire Ltd", rate: FACTORY_SQM_RATE },
      { name: "LIDA TEXTILE AND DYEING LTD", rate: FACTORY_SQM_RATE },
      { name: "Magic Works Ltd", rate: FACTORY_SQM_RATE },
      { name: "Mahdeen Sweaters Ltd", rate: FACTORY_SQM_RATE },
      { name: "MG Knit Flair Ltd", rate: FACTORY_SQM_RATE },
      { name: "Modele De Capital Ind Ltd", rate: FACTORY_SQM_RATE },
      { name: "Newage Apparels Limited", rate: FACTORY_SQM_RATE },
      { name: "NORP KNIT INDUSTRIES LTD", rate: FACTORY_SQM_RATE },
      { name: "Panasia Clothing Ltd", rate: FACTORY_SQM_RATE },
      { name: "PN Composite Ltd", rate: FACTORY_SQM_RATE },
      { name: "Progress Apparel (Bangladesh) Ltd", rate: FACTORY_SQM_RATE },
      { name: "REMI HOLDINGS LTD", rate: FACTORY_SQM_RATE },
      { name: "SCARLET KNITWEARS LTD", rate: FACTORY_SQM_RATE },
      { name: "Shanta Denims Ltd", rate: FACTORY_SQM_RATE },
      { name: "Shanta Industries Ltd", rate: FACTORY_SQM_RATE },
      { name: "STYRAX FASHIONS LIMITED", rate: FACTORY_SQM_RATE },
      { name: "Surma Garments Ltd", rate: FACTORY_SQM_RATE },
      { name: "Tarasima Appareals Ltd", rate: FACTORY_SQM_RATE },
      { name: "Target Denim & Casual Wear Ltd", rate: FACTORY_SQM_RATE },
      { name: "Target Fine Wear Industries Ltd", rate: FACTORY_SQM_RATE },
      { name: "T-Design Knitwear Ltd", rate: FACTORY_SQM_RATE },
      { name: "Unifa Handbag & Belt (BD) Co Ltd", rate: FACTORY_SQM_RATE },
      { name: "Universal Menswear Ltd", rate: FACTORY_SQM_RATE },
      { name: "Urmi Garments Limited", rate: FACTORY_SQM_RATE },
      { name: "VICTORIA INTIMATE LTD", rate: FACTORY_SQM_RATE },
      { name: "Windy Apparels Ltd", rate: FACTORY_SQM_RATE }
    ]
  },
  uniglory: {
    name: "Uniglory",
    formulaId: "uniglory",
    factories: [
      { name: "AB APPARELS LTD", rate: FACTORY_SQM_RATE },
      { name: "Crown Exclusive Wears", rate: FACTORY_SQM_RATE },
      { name: "Faiza Ind", rate: FACTORY_SQM_RATE },
      { name: "Far East Knitting", rate: FACTORY_SQM_RATE },
      { name: "Golden Refit Garments", rate: FACTORY_SQM_RATE },
      { name: "Ibrahim Knit Garments (PVT) Ltd.", rate: FACTORY_SQM_RATE },
      { name: "Libas Textiles Limited", rate: FACTORY_SQM_RATE },
      { name: "Neo Fashion Limited.", rate: FACTORY_SQM_RATE },
      { name: "Target Fine Wear", rate: FACTORY_SQM_RATE },
      { name: "Yunusco (BD) Ltd", rate: FACTORY_SQM_RATE },
      { name: "AFIYA KNITWEAR LTD.", rate: FACTORY_SQM_RATE },
      { name: "Ananta Huxing", rate: FACTORY_SQM_RATE },
      { name: "AST Knit", rate: FACTORY_SQM_RATE },
      { name: "Azmat Apparels Ltd.", rate: FACTORY_SQM_RATE },
      { name: "Comfit Composite Knit Ltd", rate: FACTORY_SQM_RATE },
      { name: "Echotex Ltd", rate: FACTORY_SQM_RATE },
      { name: "Entrust Fashions Ltd.", rate: FACTORY_SQM_RATE },
      { name: "Glory Fashion Wear Ltd.", rate: FACTORY_SQM_RATE },
      { name: "Golden Refit Garments", rate: FACTORY_SQM_RATE },
      { name: "HELICON LIMITED", rate: FACTORY_SQM_RATE },
      { name: "Mahdeen Sweaters Ltd.", rate: FACTORY_SQM_RATE },
      { name: "NKM FASHION LTD.", rate: FACTORY_SQM_RATE },
      { name: "Novel Hurricane Knit Ltd.", rate: FACTORY_SQM_RATE },
      { name: "Winter Dress Ltd", rate: FACTORY_SQM_RATE },
      { name: "Southern Clothing", rate: FACTORY_SQM_RATE },
      { name: "ATS Apparels", rate: FACTORY_SQM_RATE },
      { name: "CA Knit", rate: FACTORY_SQM_RATE },
      { name: "Colors & Stitchs", rate: FACTORY_SQM_RATE },
      { name: "Colour & Co. Ltd.", rate: FACTORY_SQM_RATE },
      { name: "Fakir Apparels", rate: FACTORY_SQM_RATE },
      { name: "Echotex Ltd", rate: FACTORY_SQM_RATE },
      { name: "Fortis Garments Ltd", rate: FACTORY_SQM_RATE },
      { name: "GM Apparels Limited", rate: FACTORY_SQM_RATE },
      { name: "Goumati Knit Wears", rate: FACTORY_SQM_RATE },
      { name: "Intimate Attire Limited", rate: FACTORY_SQM_RATE },
      { name: "Kaixi Fashion", rate: FACTORY_SQM_RATE },
      { name: "Lida Textiles", rate: FACTORY_SQM_RATE },
      { name: "Magic Works Ltd.", rate: FACTORY_SQM_RATE },
      { name: "MB Knit Fashion Limited", rate: FACTORY_SQM_RATE },
      { name: "Model De Capital", rate: FACTORY_SQM_RATE },
      { name: "Needle Drop Limited.", rate: FACTORY_SQM_RATE },
      { name: "New Asia Fashions", rate: FACTORY_SQM_RATE },
      { name: "Newage App", rate: FACTORY_SQM_RATE },
      { name: "Onus Design", rate: FACTORY_SQM_RATE },
      { name: "Reaz Export Apparels", rate: FACTORY_SQM_RATE },
      { name: "Rose Intimate", rate: FACTORY_SQM_RATE },
      { name: "SB Style", rate: FACTORY_SQM_RATE },
      { name: "Scarlet Knitwears Ltd", rate: FACTORY_SQM_RATE },
      { name: "Southeast Sweater Ltd", rate: FACTORY_SQM_RATE },
      { name: "SOUTHERN KNITWEAR", rate: FACTORY_SQM_RATE },
      { name: "Urmi Garments", rate: FACTORY_SQM_RATE },
      { name: "Tropical Knit", rate: FACTORY_SQM_RATE },
      { name: "Victoria Intimate Ltd", rate: FACTORY_SQM_RATE },
      { name: "Welldone Apparels Ltd.", rate: FACTORY_SQM_RATE },
      { name: "Winter Dress", rate: FACTORY_SQM_RATE }
    ]
  },
  ps_union: {
    name: "UNION LABEL & ACCESSORIES LTD.",
    formulaId: "union",
    factories: [
      { name: "WINTER DRESS LTD.", rate: FACTORY_SQM_RATE },
      { name: "HASAN TANVIR FASHION WEAR LTD.", rate: FACTORY_SQM_RATE },
      { name: "NORP KNIT IND.", rate: FACTORY_SQM_RATE },
      { name: "SB STYLE COMPOSITE LTD.", rate: FACTORY_SQM_RATE },
      { name: "MOUCHAK KNIT COMPOSITE LTD.", rate: FACTORY_SQM_RATE },
      { name: "JIN HONG GARMENTS LTD.", rate: FACTORY_SQM_RATE },
      { name: "SOUTHERN KNIT WEAR LTD.", rate: FACTORY_SQM_RATE },
      { name: "GOLDEN REFIT LTD.", rate: FACTORY_SQM_RATE },
      { name: "AXIS KNIT WAER LTD.", rate: FACTORY_SQM_RATE },
      { name: "ECHOKNITS LTD.", rate: FACTORY_SQM_RATE },
      { name: "TARGET DENIM & CASUAL WEAR LTD.", rate: FACTORY_SQM_RATE },
      { name: "MODEL DE CAPITAL.", rate: FACTORY_SQM_RATE },
      { name: "L,ESQUIRE LTD.", rate: FACTORY_SQM_RATE },
      { name: "CHORKA TEXTILE LTD.", rate: FACTORY_SQM_RATE },
      { name: "RIZVI FASHION LTD.", rate: FACTORY_SQM_RATE },
      { name: "WELLDONE APPARELS LTD.", rate: FACTORY_SQM_RATE },
      { name: "CROWN EXCLUSIVE LTD.", rate: FACTORY_SQM_RATE },
      { name: "MG NICHE FLAIR LTD.", rate: FACTORY_SQM_RATE },
      { name: "APS APPARELS LTD.", rate: FACTORY_SQM_RATE }
    ]
  }
};

const CARTON_PRESETS = [
  { id: "495x285x375", label: "495 x 285 x 375", l: 495, w: 285, h: 375 },
  { id: "480x360x150", label: "480 x 360 x 150", l: 480, w: 360, h: 150 },
  { id: "380x340x150", label: "380 x 340 x 150", l: 380, w: 340, h: 150 },
  { id: "480x320x280", label: "480 x 320 x 280", l: 480, w: 320, h: 280 },
  { id: "550x340x260", label: "550 x 340 x 260", l: 550, w: 340, h: 260 },
  { id: "600x400x150", label: "600 x 400 x 150", l: 600, w: 400, h: 150 },
  { id: "770x430x240", label: "770 x 430 x 240", l: 770, w: 430, h: 240 },
  { id: "630x320x350", label: "630 x 320 x 350", l: 630, w: 320, h: 350 },
  { id: "540x300x260", label: "540 x 300 x 260", l: 540, w: 300, h: 260 },
  { id: "500x380x290", label: "500 x 380 x 290", l: 500, w: 380, h: 290 },
  { id: "800x600x500", label: "800 x 600 x 500", l: 800, w: 600, h: 500 }
];
