const PRIMARK_SQM_RATE = 0.77;
const FACTORY_SQM_RATE = PRIMARK_SQM_RATE * 0.95;

const SUPPLIERS = {
  epyllion: {
    name: "Epyllion Limited",
    formulaId: "epyllion",
    factories: [
      { name: "Fakir Knitwears Ltd PJT (14100)", rate: FACTORY_SQM_RATE },
      { name: "Well Lord Knit Wears Ltd (25086)", rate: FACTORY_SQM_RATE },
      { name: "Novel Hurricane Knit Garments Ltd PJT (18469)", rate: FACTORY_SQM_RATE },
      { name: "Hasan Tanvir Fashion Wears Ltd PJT (19151)", rate: FACTORY_SQM_RATE },
      { name: "Mouchak Knit Composite Ltd PJT (20227)", rate: FACTORY_SQM_RATE },
      { name: "Habitus Fashion Ltd (20147)", rate: FACTORY_SQM_RATE },
      { name: "Lesquire Limited (26569)", rate: FACTORY_SQM_RATE },
      { name: "Ibrahim Knit Garments Pvt Ltd PJT (12048)", rate: FACTORY_SQM_RATE },
      { name: "Surma Garments Ltd PJT (18926)", rate: FACTORY_SQM_RATE },
      { name: "Prudent Fashions Ltd (25696)", rate: FACTORY_SQM_RATE },
      { name: "Norp Knit Industries Limited Unit 1 PJT (18750)", rate: FACTORY_SQM_RATE },
      { name: "Mehnaz Styles & Craft Ltd (23609)", rate: FACTORY_SQM_RATE },
      { name: "Modele De Capital Ind Ltd PJT (11277)", rate: FACTORY_SQM_RATE },
      { name: "AST Knitwear Ltd PJT (14482)", rate: FACTORY_SQM_RATE },
      { name: "Fortis Garments Limited (25218)", rate: FACTORY_SQM_RATE },
      { name: "Soorty Textiles BD Limited PJT (20079)", rate: FACTORY_SQM_RATE },
      { name: "Masco Cotton Ltd (17443)", rate: FACTORY_SQM_RATE },
      { name: "Fame Apparels Ltd (25042)", rate: FACTORY_SQM_RATE },
      { name: "Kaixi Lingerie Bangladesh Co Ltd (27618)", rate: FACTORY_SQM_RATE },
      { name: "Triple Apparels Limited (25968)", rate: FACTORY_SQM_RATE },
      { name: "Oxford Shirts Ltd (26764)", rate: FACTORY_SQM_RATE },
      { name: "Comfit Composite Knit Ltd PKA Comfit Lingerie Limited", rate: FACTORY_SQM_RATE },
      { name: "Echotex Ltd PJT (11583)", rate: FACTORY_SQM_RATE },
      { name: "Scarlet Knitwears Ltd PJT (17803)", rate: FACTORY_SQM_RATE },
      { name: "Yunusco BD Limited (23378)", rate: FACTORY_SQM_RATE },
      { name: "International Classic Composite Ltd (19424)", rate: FACTORY_SQM_RATE },
      { name: "GoodEarth Apparels Ltd (24650)", rate: FACTORY_SQM_RATE },
      { name: "MB Knit Fashion PJT (19683)", rate: FACTORY_SQM_RATE },
      { name: "Alim Knit Ltd (20331)", rate: FACTORY_SQM_RATE },
      { name: "Progress Apparels Bangladesh Ltd (25399)", rate: FACTORY_SQM_RATE }
    ]
  },
  mu: {
    name: "M&U Packaging Ltd",
    formulaId: "mu",
    factories: [
      { name: "AKH Eco Apparels Ltd PJT (20979)", rate: FACTORY_SQM_RATE },
      { name: "Ananta Casual Wear Ltd (27725)", rate: FACTORY_SQM_RATE },
      { name: "Ananta Huaxiang Ltd (20421)", rate: FACTORY_SQM_RATE },
      { name: "Aspire Garments Ltd PJT (24040)", rate: FACTORY_SQM_RATE },
      { name: "Azmat Apparels Ltd (24634)", rate: FACTORY_SQM_RATE },
      { name: "Bando Eco Apparels Ltd (24450)", rate: FACTORY_SQM_RATE },
      { name: "Bravo Apparel Manufacturer Ltd (26055)", rate: FACTORY_SQM_RATE },
      { name: "Brothers Fashion LTD (26005)", rate: FACTORY_SQM_RATE },
      { name: "CA Knitwear Ltd (25383)", rate: FACTORY_SQM_RATE },
      { name: "Chorka Textile Limited PJT (18757)", rate: FACTORY_SQM_RATE },
      { name: "Colour And Co (27649)", rate: FACTORY_SQM_RATE },
      { name: "Designtex Knitwear Ltd (24601)", rate: FACTORY_SQM_RATE },
      { name: "Echoknits Ltd (26559)", rate: FACTORY_SQM_RATE },
      { name: "Fortis Garments Limited (25218)", rate: FACTORY_SQM_RATE },
      { name: "Goumati Knit Wears Ltd", rate: FACTORY_SQM_RATE },
      { name: "Habitus Fashion Ltd (20147)", rate: FACTORY_SQM_RATE },
      { name: "Hop Lun Apparel Limited PJT (18001)", rate: FACTORY_SQM_RATE },
      { name: "Intimate Attire Ltd PJT (23817)", rate: FACTORY_SQM_RATE },
      { name: "Lida Textile & Dyeing Limited (22400)", rate: FACTORY_SQM_RATE },
      { name: "Magic Works (26306)", rate: FACTORY_SQM_RATE },
      { name: "Mahdeen Sweater Ltd (15379)", rate: FACTORY_SQM_RATE },
      { name: "MG Knit Flair Ltd", rate: FACTORY_SQM_RATE },
      { name: "Modele De Capital Ind Ltd PJT (11277)", rate: FACTORY_SQM_RATE },
      { name: "Newage Apparels Ltd (14512)", rate: FACTORY_SQM_RATE },
      { name: "Norp Knit Industries Limited Unit 1 PJT (18750)", rate: FACTORY_SQM_RATE },
      { name: "Panasia Clothing Ltd PJT (22257)", rate: FACTORY_SQM_RATE },
      { name: "PN Composite (14279)", rate: FACTORY_SQM_RATE },
      { name: "Progress Apparels Bangladesh Ltd (25399)", rate: FACTORY_SQM_RATE },
      { name: "Remi Holdings Limited PJT (21282)", rate: FACTORY_SQM_RATE },
      { name: "Scarlet Knitwears Ltd PJT (17803)", rate: FACTORY_SQM_RATE },
      { name: "Shanta Denims Limited (22933)", rate: FACTORY_SQM_RATE },
      { name: "Shanta Industries Ltd", rate: FACTORY_SQM_RATE },
      { name: "Styrax Fashions Ltd Plot 180 (27586)", rate: FACTORY_SQM_RATE },
      { name: "Surma Garments Ltd PJT (18926)", rate: FACTORY_SQM_RATE },
      { name: "Tarasima Apparels Ltd (17830)", rate: FACTORY_SQM_RATE },
      { name: "Target Denim & Casual Wear Ltd PJT (23925)", rate: FACTORY_SQM_RATE },
      { name: "Target Fine Wear Industries Ltd", rate: FACTORY_SQM_RATE },
      { name: "T Design Knitwear Limited (24250)", rate: FACTORY_SQM_RATE },
      { name: "Unifa Handbag And Belt (BD) Co Ltd (27672)", rate: FACTORY_SQM_RATE },
      { name: "Universal Menswear Ltd (19336)", rate: FACTORY_SQM_RATE },
      { name: "Urmi Garments Limited", rate: FACTORY_SQM_RATE },
      { name: "Victoria Intimate Ltd (26293)", rate: FACTORY_SQM_RATE },
      { name: "Windy Apparels Ltd (20096)", rate: FACTORY_SQM_RATE }
    ]
  },
  uniglory: {
    name: "Uniglory Paper & Packaging",
    formulaId: "uniglory",
    factories: [
      { name: "AB Apparels Ltd (24718)", rate: FACTORY_SQM_RATE },
      { name: "Crown Exclusive Wears Ltd (24272)", rate: FACTORY_SQM_RATE },
      { name: "Faiza Industries Ltd (24407)", rate: FACTORY_SQM_RATE },
      { name: "Far East Knitting & Dyeing Industries Ltd PJT (115)", rate: FACTORY_SQM_RATE },
      { name: "Golden Refit Garments Ltd (23489)", rate: FACTORY_SQM_RATE },
      { name: "Ibrahim Knit Garments Pvt Ltd PJT (12048)", rate: FACTORY_SQM_RATE },
      { name: "Libas Textiles Ltd (13809)", rate: FACTORY_SQM_RATE },
      { name: "Neo Fashion Ltd (18983)", rate: FACTORY_SQM_RATE },
      { name: "Target Fine Wear", rate: FACTORY_SQM_RATE },
      { name: "Yunusco BD Limited (23378)", rate: FACTORY_SQM_RATE },
      { name: "Afiya Knitwear Ltd PJT (20517)", rate: FACTORY_SQM_RATE },
      { name: "Ananta Huaxiang Ltd (20421)", rate: FACTORY_SQM_RATE },
      { name: "AST Knitwear Ltd PJT (14482)", rate: FACTORY_SQM_RATE },
      { name: "Azmat Apparels Ltd (24634)", rate: FACTORY_SQM_RATE },
      { name: "Comfit Composite Knit Ltd PKA Comfit Lingerie Limited", rate: FACTORY_SQM_RATE },
      { name: "Echotex Ltd PJT (11583)", rate: FACTORY_SQM_RATE },
      { name: "Entrust Fashions Ltd.", rate: FACTORY_SQM_RATE },
      { name: "Glory Fashion Wear Ltd (21750)", rate: FACTORY_SQM_RATE },
      { name: "Golden Refit Garments Ltd (23489)", rate: FACTORY_SQM_RATE },
      { name: "HELICON LIMITED", rate: FACTORY_SQM_RATE },
      { name: "Mahdeen Sweater Ltd (15379)", rate: FACTORY_SQM_RATE },
      { name: "NKM FASHION LTD.", rate: FACTORY_SQM_RATE },
      { name: "Novel Hurricane Knit Garments Ltd PJT (18469)", rate: FACTORY_SQM_RATE },
      { name: "Winter Dress (26695)", rate: FACTORY_SQM_RATE },
      { name: "Southern Clothings Ltd PJT (16534)", rate: FACTORY_SQM_RATE },
      { name: "ATS Apparels Ltd (11121)", rate: FACTORY_SQM_RATE },
      { name: "CA Knitwear Ltd (25383)", rate: FACTORY_SQM_RATE },
      { name: "Colors & Stitches Limited (24447)", rate: FACTORY_SQM_RATE },
      { name: "Colour And Co (27649)", rate: FACTORY_SQM_RATE },
      { name: "Fakir Apparels Ltd PJT (11266)", rate: FACTORY_SQM_RATE },
      { name: "Echotex Ltd PJT (11583)", rate: FACTORY_SQM_RATE },
      { name: "Fortis Garments Limited (25218)", rate: FACTORY_SQM_RATE },
      { name: "GM Apparels Ltd (25787)", rate: FACTORY_SQM_RATE },
      { name: "Goumati Knit Wears", rate: FACTORY_SQM_RATE },
      { name: "Intimate Attire Ltd PJT (23817)", rate: FACTORY_SQM_RATE },
      { name: "Kaixi Fashion Bangladesh Co Ltd (26163)", rate: FACTORY_SQM_RATE },
      { name: "Lida Textile & Dyeing Limited (22400)", rate: FACTORY_SQM_RATE },
      { name: "Magic Works (26306)", rate: FACTORY_SQM_RATE },
      { name: "MB Knit Fashion PJT (19683)", rate: FACTORY_SQM_RATE },
      { name: "Modele De Capital Ind Ltd PJT (11277)", rate: FACTORY_SQM_RATE },
      { name: "Needle Drop Ltd (20159)", rate: FACTORY_SQM_RATE },
      { name: "New Asia Fashions Limited (26015)", rate: FACTORY_SQM_RATE },
      { name: "Newage Apparels Ltd (14512)", rate: FACTORY_SQM_RATE },
      { name: "Onus Design Ltd PKA Onus Garments Ltd (25438)", rate: FACTORY_SQM_RATE },
      { name: "Reaz Export Apparels Ltd PJT (15173)", rate: FACTORY_SQM_RATE },
      { name: "Rose Intimates Ltd PJT (23445)", rate: FACTORY_SQM_RATE },
      { name: "SB Style Composite Ltd PJT (17149)", rate: FACTORY_SQM_RATE },
      { name: "Scarlet Knitwears Ltd PJT (17803)", rate: FACTORY_SQM_RATE },
      { name: "Southeast Sweaters Limited PJT (23926)", rate: FACTORY_SQM_RATE },
      { name: "Southern Knitwear Limited (27035)", rate: FACTORY_SQM_RATE },
      { name: "Urmi Garments", rate: FACTORY_SQM_RATE },
      { name: "Tropical Knitex Ltd (24442)", rate: FACTORY_SQM_RATE },
      { name: "Victoria Intimate Ltd (26293)", rate: FACTORY_SQM_RATE },
      { name: "Welldone Apparels Ltd.", rate: FACTORY_SQM_RATE },
      { name: "Winter Dress (26695)", rate: FACTORY_SQM_RATE }
    ]
  },
  ps_union: {
    name: "UNION LABEL & ACCESSORIES LTD.",
    formulaId: "union",
    factories: [
      { name: "Winter Dress (26695)", rate: FACTORY_SQM_RATE },
      { name: "Hasan Tanvir Fashion Wears Ltd PJT (19151)", rate: FACTORY_SQM_RATE },
      { name: "Norp Knit Industries Limited Unit 1 PJT (18750)", rate: FACTORY_SQM_RATE },
      { name: "SB Style Composite Ltd PJT (17149)", rate: FACTORY_SQM_RATE },
      { name: "Mouchak Knit Composite Ltd PJT (20227)", rate: FACTORY_SQM_RATE },
      { name: "JIN HONG GARMENTS LTD.", rate: FACTORY_SQM_RATE },
      { name: "Southern Knitwear Limited (27035)", rate: FACTORY_SQM_RATE },
      { name: "Golden Refit Garments Ltd (23489)", rate: FACTORY_SQM_RATE },
      { name: "Axis Knitwears Limited (26006)", rate: FACTORY_SQM_RATE },
      { name: "Echoknits Ltd (26559)", rate: FACTORY_SQM_RATE },
      { name: "Target Denim & Casual Wear Ltd PJT (23925)", rate: FACTORY_SQM_RATE },
      { name: "Modele De Capital Ind Ltd PJT (11277)", rate: FACTORY_SQM_RATE },
      { name: "Lesquire Limited (26569)", rate: FACTORY_SQM_RATE },
      { name: "Chorka Textile Limited PJT (18757)", rate: FACTORY_SQM_RATE },
      { name: "Rizvi Fashions Limited PJT (21111)", rate: FACTORY_SQM_RATE },
      { name: "WELLDONE APPARELS LTD.", rate: FACTORY_SQM_RATE },
      { name: "Crown Exclusive Wears Ltd (24272)", rate: FACTORY_SQM_RATE },
      { name: "MG Niche Stitch Limited PJT (21531)", rate: FACTORY_SQM_RATE },
      { name: "APS Apparels Limited (26018)", rate: FACTORY_SQM_RATE }
    ]
  }
};

const CARTON_PRESETS = [
  { id: "495x285x375", label: "495 x 285 x 375", l: 495, w: 285, h: 375 },
  { id: "480x360x150", label: "480 x 360 x 150", l: 480, w: 360, h: 150 },
  { id: "380x340x150", label: "380 x 340 x 150", l: 380, w: 340, h: 150 },
  { id: "480x320x280", label: "480 x 320 x 280", l: 480, w: 320, h: 280 },
  { id: "550x340x260", label: "550 x 340 x 260", l: 550, w: 340, h: 260 },
  { id: "600x400x150", label: "600 x 400 x 150", l: 600, w: 400, h: 150 },
  { id: "770x430x240", label: "770 x 430 x 240", l: 770, w: 430, h: 240 },
  { id: "630x320x350", label: "630 x 320 x 350", l: 630, w: 320, h: 350 },
  { id: "540x300x260", label: "540 x 300 x 260", l: 540, w: 300, h: 260 },
  { id: "500x380x290", label: "500 x 380 x 290", l: 500, w: 380, h: 290 },
  { id: "800x600x500", label: "800 x 600 x 500", l: 800, w: 600, h: 500 }
];
