const SUPPLIERS = {
  epyllion: {
    name: "Epyllion",
    formulaId: "epyllion",
    factories: [
      { name: "Fakir Knitwears Ltd.", rate: 0.70 },
      { name: "Well Lord Knitwear Limited", rate: 0.78 },
      { name: "Novel Hurricane Knit Garments Ltd.", rate: 0.78 },
      { name: "Hasan Tanvir Fashion Wears Limited", rate: 0.68 },
      { name: "MOUCHAK KNIT COMPOSITE LTD", rate: 0.66 },
      { name: "Habitus Fashions Limited", rate: 0.73 },
      { name: "L'ESQUIRE LIMITED", rate: 0.68 },
      { name: "Ibrahim Knit Garments (Pvt) Ltd.", rate: 0.69 },
      { name: "Surma Garments LTD", rate: 0.71 },
      { name: "PRUDENT FASHION LTD.", rate: 0.74 },
      { name: "Norp Knit Industries Ltd.", rate: 0.74 },
      { name: "Mehnaz Styles and Craft Ltd.", rate: 0.68 },
      { name: "Modele de Capital Ind Ltd.", rate: 0.72 },
      { name: "AST Knitwear Ltd.", rate: 0.78 },
      { name: "Fortis Garments Limited", rate: 0.73 },
      { name: "Soorty Textiles (BD) Limited", rate: 0.70 },
      { name: "Masco Cottons Ltd.", rate: 0.65 },
      { name: "Fame Apparels Limited", rate: 0.65 },
      { name: "Kaixi Lingerie Bangladesh Co. Limited", rate: 0.70 },
      { name: "Triple Apparels Limited", rate: 0.68 },
      { name: "Oxford Shirts Limited", rate: 0.75 },
      { name: "Comfit Composite Knit Limited", rate: 0.70 },
      { name: "Echotex Limited", rate: 0.68 },
      { name: "Scarlet Knitwears Limited", rate: 0.74 },
      { name: "Yunusco (BD) Ltd.", rate: 0.69 },
      { name: "International Classic Composite Limited", rate: 0.66 },
      { name: "Good Earth Apparels ltd.", rate: 0.73 },
      { name: "MB Knit Fashion Limited", rate: 0.72 },
      { name: "ALIM KNIT (BD) LTD.", rate: 0.67 },
      { name: "Progress Apparels (Bangladesh) Limited", rate: 0.75 }
    ]
  },
  mu: {
    name: "M&U",
    formulaId: "mu",
    factories: [
      { name: "Akh Eco Apparels Ltd", rate: 0.96 },
      { name: "Ananta Casual Wear Ltd", rate: 0.85 },
      { name: "Ananta Huaxiang Ltd", rate: 0.75 },
      { name: "Aspire Garments Ltd", rate: 0.70 },
      { name: "Azmat Apparels Ltd", rate: 0.74 },
      { name: "BANDO Eco Apparels Ltd", rate: 0.82 },
      { name: "BRAVO APPAREL MANUFACTURER LTD", rate: 0.75 },
      { name: "Brothers Fashion Ltd", rate: 0.75 },
      { name: "CA KNITWEAR LIMITED", rate: 0.75 },
      { name: "Chorka Textile Ltd", rate: 0.80 },
      { name: "COLOUR AND CO LTD", rate: 0.73 },
      { name: "Designtex Knitwear Ltd", rate: 0.74 },
      { name: "ECHOKNITS Ltd", rate: 0.75 },
      { name: "Fortis Garments Ltd", rate: 0.75 },
      { name: "Goumati Knit Wears Ltd", rate: 0.72 },
      { name: "Habitus Fashion Limited", rate: 0.75 },
      { name: "Hoplun Apparels Ltd", rate: 0.75 },
      { name: "Intimate Attire Ltd", rate: 0.74 },
      { name: "LIDA TEXTILE AND DYEING LTD", rate: 0.73 },
      { name: "Magic Works Ltd", rate: 0.75 },
      { name: "Mahdeen Sweaters Ltd", rate: 0.80 },
      { name: "MG Knit Flair Ltd", rate: 0.80 },
      { name: "Modele De Capital Ind Ltd", rate: 0.72 },
      { name: "Newage Apparels Limited", rate: 0.75 },
      { name: "NORP KNIT INDUSTRIES LTD", rate: 0.74 },
      { name: "Panasia Clothing Ltd", rate: 0.80 },
      { name: "PN Composite Ltd", rate: 0.75 },
      { name: "Progress Apparel (Bangladesh) Ltd", rate: 0.75 },
      { name: "REMI HOLDINGS LTD", rate: 0.77 },
      { name: "SCARLET KNITWEARS LTD", rate: 0.74 },
      { name: "Shanta Denims Ltd", rate: 0.76 },
      { name: "Shanta Industries Ltd", rate: 0.76 },
      { name: "STYRAX FASHIONS LIMITED", rate: 0.75 },
      { name: "Surma Garments Ltd", rate: 0.72 },
      { name: "Tarasima Appareals Ltd", rate: 0.77 },
      { name: "Target Denim & Casual Wear Ltd", rate: 0.77 },
      { name: "Target Fine Wear Industries Ltd", rate: 0.77 },
      { name: "T-Design Knitwear Ltd", rate: 0.74 },
      { name: "Unifa Handbag & Belt (BD) Co Ltd", rate: 0.76 },
      { name: "Universal Menswear Ltd", rate: 0.76 },
      { name: "Urmi Garments Limited", rate: 0.75 },
      { name: "VICTORIA INTIMATE LTD", rate: 0.75 },
      { name: "Windy Apparels Ltd", rate: 0.73 }
    ]
  },
  uniglory: {
    name: "Uniglory",
    formulaId: "uniglory",
    factories: [
      { name: "AB APPARELS LTD", rate: 0.78 },
      { name: "Crown Exclusive Wears", rate: 0.72 },
      { name: "Faiza Ind", rate: 0.72 },
      { name: "Far East Knitting", rate: 0.72 },
      { name: "Golden Refit Garments", rate: 0.72 },
      { name: "Ibrahim Knit Garments (PVT) Ltd.", rate: 0.72 },
      { name: "Libas Textiles Limited", rate: 0.72 },
      { name: "Neo Fashion Limited.", rate: 0.72 },
      { name: "Target Fine Wear", rate: 0.74 },
      { name: "Yunusco (BD) Ltd", rate: 0.72 },
      { name: "AFIYA KNITWEAR LTD.", rate: 0.72 },
      { name: "Ananta Huxing", rate: 0.76 },
      { name: "AST Knit", rate: 0.76 },
      { name: "Azmat Apparels Ltd.", rate: 0.76 },
      { name: "Comfit Composite Knit Ltd", rate: 0.72 },
      { name: "Echotex Ltd", rate: 0.73 },
      { name: "Entrust Fashions Ltd.", rate: 0.72 },
      { name: "Glory Fashion Wear Ltd.", rate: 0.72 },
      { name: "Golden Refit Garments", rate: 0.72 },
      { name: "HELICON LIMITED", rate: 0.73 },
      { name: "Mahdeen Sweaters Ltd.", rate: 0.73 },
      { name: "NKM FASHION LTD.", rate: 0.72 },
      { name: "Novel Hurricane Knit Ltd.", rate: 0.75 },
      { name: "Winter Dress Ltd", rate: 0.72 },
      { name: "Southern Clothing", rate: 0.72 },
      { name: "ATS Apparels", rate: 0.75 },
      { name: "CA Knit", rate: 0.72 },
      { name: "Colors & Stitchs", rate: 0.72 },
      { name: "Colour & Co. Ltd.", rate: 0.72 },
      { name: "Fakir Apparels", rate: 0.73 },
      { name: "Echotex Ltd", rate: 0.73 },
      { name: "Fortis Garments Ltd", rate: 0.72 },
      { name: "GM Apparels Limited", rate: 0.85 },
      { name: "Goumati Knit Wears", rate: 0.72 },
      { name: "Intimate Attire Limited", rate: 0.72 },
      { name: "Kaixi Fashion", rate: 0.72 },
      { name: "Lida Textiles", rate: 0.72 },
      { name: "Magic Works Ltd.", rate: 0.72 },
      { name: "MB Knit Fashion Limited", rate: 0.72 },
      { name: "Model De Capital", rate: 0.72 },
      { name: "Needle Drop Limited.", rate: 0.72 },
      { name: "New Asia Fashions", rate: 0.72 },
      { name: "Newage App", rate: 0.72 },
      { name: "Onus Design", rate: 0.72 },
      { name: "Reaz Export Apparels", rate: 0.72 },
      { name: "Rose Intimate", rate: 0.72 },
      { name: "SB Style", rate: 0.72 },
      { name: "Scarlet Knitwears Ltd", rate: 0.72 },
      { name: "Southeast Sweater Ltd", rate: 0.85 },
      { name: "SOUTHERN KNITWEAR", rate: 0.72 },
      { name: "Urmi Garments", rate: 0.70 },
      { name: "Tropical Knit", rate: 0.72 },
      { name: "Victoria Intimate Ltd", rate: 0.72 },
      { name: "Welldone Apparels Ltd.", rate: 0.72 },
      { name: "Winter Dress", rate: 0.72 }
    ]
  }
};

const CARTON_PRESETS = [
  { id: "495x285x375", label: "495 x 285 x 375", l: 495, w: 285, h: 375 },
  { id: "480x360x150", label: "480 x 360 x 150", l: 480, w: 360, h: 150 },
  { id: "380x340x150", label: "380 x 340 x 150", l: 380, w: 340, h: 150 },
  { id: "480x320x280", label: "480 x 320 x 280", l: 480, w: 320, h: 280 },
  { id: "550x340x260", label: "550 x 340 x 260", l: 550, w: 340, h: 260 },
  { id: "600x400x150", label: "600 x 400 x 150", l: 600, w: 400, h: 150 },
  { id: "770x430x240", label: "770 x 430 x 240", l: 770, w: 430, h: 240 },
  { id: "630x320x350", label: "630 x 320 x 350", l: 630, w: 320, h: 350 },
  { id: "540x300x260", label: "540 x 300 x 260", l: 540, w: 300, h: 260 },
  { id: "500x380x290", label: "500 x 380 x 290", l: 500, w: 380, h: 290 },
  { id: "800x600x500", label: "800 x 600 x 500", l: 800, w: 600, h: 500 }
];
